// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Feedback: typeof import('./src/components/feedback/index.vue')['default']
    GithubCorner: typeof import('./src/components/github-corner/index.vue')['default']
    LazyloadImage: typeof import('./src/components/lazyload-image/index.vue')['default']
    Search: typeof import('./src/components/search/index.vue')['default']
  }
}
