title: 烙馍网
icon: fa-lightbulb-o
subMenu:
  - title: 网站
    links:
      - title: 关注地方生活服务
        description: 烙馍网关注地方小吃、美食、旅游、人文、文化、时尚、设计、休闲、娱乐、宠物、工作，是一个关于地方特色介绍的网站，包括为您提供最新最美味的小吃美食知识和技巧，以及有关小吃的历史和文化背景。烙馍（luò mó）是徐州一种特色传统面食，已有着2000多年的历史，类似煎饼又和煎饼不同，烙馍是用未发酵的面粉和成柔软的面团。
        url: https://www.luomor.com/
        logo: "https://www.luomor.com/favicon.ico"
      - title: 文心AIGC - 人工智能ChatGPT
        description: 文心AIGC，AIGC指利用人工智能技术来生成内容，其中包括文字、语音、代码、图像、视频、机器人动作等等。被认为是继PGC、UGC之后的新型内容创作方式。AIGC作为元宇宙的新方向，近几年迭代速度呈现指数级爆发，谷歌、Meta、百度等平台型巨头持续布局。
        url: https://aigc.luomor.com/
        logo: "https://aigc.luomor.com/favicon.ico"
      - title: 烙馍网 - 游戏导航
        description: 游戏导航
        url: https://games.luomor.com/
        logo: "https://games.luomor.com/favicon.ico"
      - title: 烙馍网 - 应用导航
        description: 应用导航
        url: https://apps.luomor.com/
        logo: "https://apps.luomor.com/favicon.ico"
  - title: 电商
    links:
      - title: 烙馍省钱-优惠券领取
        description: 烙馍省钱官网-每日更新天猫淘宝优惠券，更有9.9包邮专区，品牌优选，找券功能齐全。聚划算的优惠券，淘实惠的购物网站，大品牌商品可享折上折，各种超值商品只需一键搜索。特卖、低价、白菜价，尽在烙馍省钱
        url: https://tb-m.luomor.com/
        logo: "https://tb.luomor.com/favicon.ico"
  - title: 游戏
    links:
      - title: 2048
        description: 2048
        url: https://games.luomor.com/2048/
        logo: ""
      - title: 3D魔方
        description: 3D魔方
        url: https://games.luomor.com/cuber/
        logo: ""
      - title: 算数
        description: 算数
        url: https://games.luomor.com/math/
        logo: ""
      - title: 甜言蜜语
        description: 甜言蜜语
        url: https://games.luomor.com/sweet-words
        logo: "https://games.luomor.com/sweet-words/favicon.ico"
      - title: 心
        description: 心
        url: https://games.luomor.com/valentine/
        logo: ""
      - title: 心
        description: 心
        url: https://games.luomor.com/valentine2/
        logo: ""
      - title: 心
        description: 心
        url: https://games.luomor.com/valentine3/
        logo: ""
      - title: 坦克大战（pc）
        description: 坦克大战（pc）
        url: https://games.luomor.com/battle-city/
        logo: ""
      - title: 猜灯谜（pc）
        description: 猜灯谜（pc）
        url: https://games.luomor.com/lantern-festival/riddles.html
        logo: ""
      - title: 翻牌
        description: 翻牌
        url: https://games.luomor.com/memory/
        logo: "https://games.luomor.com/memory/favicon.ico"
      - title: 一起答题（mobile）
        description: 一起答题（mobile）
        url: https://games.luomor.com/quiz-game
        logo: ""
      - title: 俄罗斯方块
        description: 俄罗斯方块
        url: https://games.luomor.com/tetris/
        logo: ""
      - title: 合成
        description: 合成
        url: https://games.luomor.com/big-watermelon/
        logo: ""
      - title: 口红游戏
        description: 口红游戏
        url: https://games.luomor.com/lipstick-game/
        logo: ""
      - title: 心
        description: 心
        url: https://games.luomor.com/most-loving-day/heart.html
        logo: ""
      - title: 贪吃蛇（pc）
        description: 通过人脸控制
        url: https://games.luomor.com/snake-face-control/
        logo: ""
      - title: 抢红包
        description: 抢红包
        url: https://games.luomor.com/car/
        logo: ""
      - title: 猪了个猪
        description: 猪了个猪
        url: https://games.luomor.com/zhulegezhu
        logo: ""
  - title: Web应用
    links:
      - title: 烙馍网 - 体验完整ChatGPT
        description: 烙馍网 ChatGPT, 体验完整ChatGPT, AI Prompt 提示词, ChatGPT 提示词, NLP 提示词, ChatGPT 指令大全
        url: https://chatgpt.luomor.com/
        logo: "https://chatgpt.luomor.com/favicon.ico"
      - title: 烙馍网 - AI Prompt 提示词
        description: AI Prompt 提示词, ChatGPT 提示词, NLP 提示词, ChatGPT 指令大全
        url: https://prompt-genius.luomor.com/
        logo: "https://prompt-genius.luomor.com/favicon.ico"
      - title: 双色球随机选号
        description: 双色球随机选号
        url: https://apps.luomor.com/lottery-color-ball/
        logo: "https://apps.luomor.com/lottery-color-ball/favicon.ico"
      - title: 双色球随机选号
        description: 双色球随机选号
        url: https://apps.luomor.com/lottery-random/
        logo: ""
      - title: 滚屏
        description: 滚屏
        url: https://apps.luomor.com/2017iwwd/
        logo: ""
      - title: 流程图（pc）
        description: 流程图（pc）
        url: https://apps.luomor.com/aiflow/
        logo: ""
      - title: 百度地图
        description: 百度地图
        url: https://apps.luomor.com/bootstrap-baidu-map/
        logo: ""
      - title: 地球
        description: 地球
        url: https://apps.luomor.com/earth/
        logo: ""
      - title: 圣诞节
        description: 圣诞节
        url: https://apps.luomor.com/xmas2020/
        logo: ""
      - title: 中国色
        description: 中国色
        url: https://apps.luomor.com/chinese-color/
        logo: "https://apps.luomor.com/chinese-color/img/favicon.ico"
      - title: AR-Emoji
        description: AR-Emoji
        url: https://apps.luomor.com/emoji-scavenger-hunt/
        logo: "https://apps.luomor.com/emoji-scavenger-hunt/img/favicon.ico"
      - title: 红包
        description: 红包
        url: https://apps.luomor.com/foolredpacket/
        logo: ""
      - title: 心
        description: 心
        url: https://apps.luomor.com/math/heart.html
        logo: ""
      - title: sin
        description: sin
        url: https://apps.luomor.com/math/sin.html
        logo: ""
      - title: curve-a
        description: curve-a
        url: https://apps.luomor.com/math/curve-a.html
        logo: ""
      - title: curve-b
        description: curve-b
        url: https://apps.luomor.com/math/curve-b.html
        logo: ""
      - title: curve-c
        description: curve-c
        url: https://apps.luomor.com/math/curve-c.html
        logo: ""
      - title: curve-d
        description: curve-d
        url: https://apps.luomor.com/math/curve-d.html
        logo: ""
      - title: curve-e
        description: curve-e
        url: https://apps.luomor.com/math/curve-e.html
        logo: ""
      - title: summary-2020
        description: summary-2020
        url: https://apps.luomor.com/summary-2020/
        logo: "https://apps.luomor.com/summary-2020/favicon.ico"
      - title: 圣诞节
        description: 圣诞节
        url: https://apps.luomor.com/xmas2021/
        logo: ""
      - title: 烙馍网-图像识别
        description: 图像识别, 中文识别
        url: https://ai-image-recognize.luomor.com/test.php
        logo: ""
  - title: AI相关
    links:
      - title: 体验完整ChatGPT
        description: 烙馍网 ChatGPT, 体验完整ChatGPT, AI Prompt 提示词, ChatGPT 提示词, NLP 提示词, ChatGPT 指令大全
        url: https://chatgpt.luomor.com/
        logo: "https://chatgpt.luomor.com/favicon.ico"
      - title: AI Prompt 提示词
        description: AI Prompt 提示词, ChatGPT 提示词, NLP 提示词, ChatGPT 指令大全
        url: https://prompt-genius.luomor.com/
        logo: "https://prompt-genius.luomor.com/favicon.ico"
